name: Publish VSCode Extension

on:
  push:
    branches:
      - production

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Match the Node.js version required by `vsce`

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Authenticate vsce using the Personal Access Token
      - name: Authenticate vsce
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx vsce publish

