name: Publish VSCode Extension

on:
  push:
    branches:
      - production

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npm install -g @vscode/vsce

      - name: Publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish

